### ISSUE TITLE
gst-av doesn't seem to work with playbin2

### ISSUE THREAD

**Issue by MaxxCorp** [felipec/gst-av#2]
What steps will reproduce the problem?
1. gst-launch playbin2 uri='...' on mpeg4/mp3/avi
2. didn't test with a directgst-av  pipeline, since i  am not sufficiently fluent in the gst pipeline syntax
3. 

What is the expected output? What do you see instead?
pipeline playing with gst-av

error indicates no fitting video decoder found, despite libgstav.so being in /usr/lib64/gstreamer-0.10

What version of the product are you using? On what operating system?
gst-av git/ libav git 07/17/2011, Fedora Rawhide 

Please provide any additional information below.
it seems as if  the plugin is blacklisted ?! At least  the word shows up in gst-inspect. Not sure how the gst autoplugging algo works, and could not immedeatly see from the gst-av code whether the plugin esports the supported mimetypes anywhere, therefore it could simply be that the autoplugging support bits are simply not yet implemented in gst-av, 
if so, please do.

**Comment by felipec** [comment]
Which version of gst-av?

Also, please try removing the cache:
 % rm ~/.gstreamer-0.10/registry.*

And then:
 % export GST_DEBUG=GST_PLUGIN_LOADING:2
 % gst-inspect av

Maybe there's a missing symbol, or something.

**Comment by MaxxCorp** [comment]
removing the registry did the trick.

I actually had included the version info: git from 7/17/2011, last included commit was b2fae76ec98a1933f3f6, the version info from the (now correctly working) gst-inspect is 0.5.3. 

There is another issue i just noticed, but should probably file a separate issue about it: in contrast to the gst-ffmpeg plugin i get a lot of 

gstbasesink.c(2866): gst_base_sink_is_too_late (): /GstPlayBin2:playbin20/GstPlaySink:playsink0/GstBin:vbin/GstAutoVideoSink:videosink/GstXvImageSink:videosink-actual-sink-xvimage:
There may be a timestamping problem, or this computer is too slow.

errors, and playback  is indeed choppy using gst-av, while being smooth using gst-ffmpeg. Not an urgent problem but maybe worth looking into.

Keep up the good work! I especially appreciate the API cruft removal aspect of your efforts

**Comment by felipec** [comment]
Could be an issue on the base sink, but perhaps there's a way to avoid that. If you find a way to reproduce, please file another bug report.

Cheers.
