### ISSUE TITLE
Annoying skipping when playing low-bitrate mp3s :( :( :(

### ISSUE THREAD

**Issue by sjn** [felipec/gst-av#4]
Seems there are a few downstream projects that suffer from audio skipping at low bitrates. I see also that there's a proposed fix for this at https://github.com/felipec/gst-av/pull/3 .

Examples of downstream problems can be seen here:
- https://together.jolla.com/question/30533/mediaplayer-fails-with-low-samplerates/
- https://together.jolla.com/question/23341/garbled-playback-of-some-mp3s-with-builtin-player/
- https://together.jolla.com/question/23013/22khz-mono-audio-stuttering-and-playback-issues/

Would it be possible to have this pull request accepted and a new release published soon?

**Comment by sjn** [comment]
Hello?

**Comment by keithzg** [comment]
@sjn You'll notice that the fix at #3 has been merged in with the official SailfishOS fork of this repo. This should thus make it into an upcoming SailfishOS release fairly soon.

**Comment by sjn** [comment]
I can report that this issue has been resolved in SailfishOS 1.1.9.28.
